project:
  type: manuscript
  render: 
    - "article.qmd"

manuscript:
  article: article.qmd

format:
  html:
    toc: true
    code-fold: true
    lightbox: auto
  # pdf:
    # cite-method: natbib # biblatex is not supported
    # keep-tex: true
    # latex-clean: false

bibliography:
  - files/bibliography/research.bib
  - files/bibexport.bib

wrap: preserve