project:
  type: website
  title: "Current Sheet Theory"
  preview: 
    port: 6007

website:
  reader-mode: true
  sidebar:
    contents: auto
  navbar:
    left:
      - text: "Home"
        href: index.qmd
    tools:
      - icon: github
        href: "https://github.com/Beforerr/cs_theory"

format:
  html:
    toc: true
    code-fold: true
    lightbox: auto

bibliography:
  - files/bibliography/research.bib

wrap: preserve